version: "3.7"
services:
  app:
    image: "funsys-app"
    build:
#      context: ./BmApiRestV2/
      dockerfile: Dockerfile
    container_name: api_spring
    depends_on:
      - db
    ports:
      - "8082:8082"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@//oracle:1521/xe
#      - SPRING_DATASOURCE_USERNAME=styk
#      - SPRING_DATASOURCE_PASSWORD=styk
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

#    networks:
#      spring-net:
#        aliases:
#          - spring-host

  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500
#    environment:
#      - ORACLE_ALLOW_REMOTE=true
#    networks:
#      spring-net:
#        aliases:
#          - db-host
#networks:
#  spring-net:
#    driver: bridge
#    ipam:
#      driver: default